name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: update submodule
              run: git submodule update --init --depth=1

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.8'

            - name: Install apt packages
              run: |
                  sudo apt-get install libeigen3-dev

            - name: Build c++ via cmake
              run: |
                  mkdir build
                  cd build
                  cmake  ..
                  make && make install

            - name: pip install pytest
              run: |
                  pip install pytest pybullet numpy

            - name: Run Pytest
              run: |
                  pytest -v tests
